package MltlOss::Model::MltlDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'MltlOss::Schema::MltlDB',
    
    connect_info => {
        dsn => 'dbi:mysql:mltl',
        user => 'MLTLOSS_user',
        password => 'MLTLUser',
    }
);

=head1 NAME

MltlOss::Model::MltlDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<MltlOss>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<MltlOss::Schema::MltlDB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.4

=head1 AUTHOR

root

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
